//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteEx.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasteEx.Resources.Resource-zh-CN", typeof(Resource_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 选择路径 的本地化字符串。
        /// </summary>
        internal static string BtnChooseLocationText {
            get {
                return ResourceManager.GetString("BtnChooseLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string BtnSaveText {
            get {
                return ResourceManager.GetString("BtnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展名: 的本地化字符串。
        /// </summary>
        internal static string LblExtensionText {
            get {
                return ResourceManager.GetString("LblExtensionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名: 的本地化字符串。
        /// </summary>
        internal static string LblFileNameText {
            get {
                return ResourceManager.GetString("LblFileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板为空，仍旧进入软件主界面？ 的本地化字符串。
        /// </summary>
        internal static string TipAnalyzeFailed {
            get {
                return ResourceManager.GetString("TipAnalyzeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在相同的文件名，是否覆盖？ 的本地化字符串。
        /// </summary>
        internal static string TipDuplicateFileName {
            get {
                return ResourceManager.GetString("TipDuplicateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到右键菜单未添加，是否添加“粘贴为文件”到系统右键菜单中？ 的本地化字符串。
        /// </summary>
        internal static string TipFirstRegister {
            get {
                return ResourceManager.GetString("TipFirstRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义扩展名规则匹配出错，请检查规则是否正确！ 的本地化字符串。
        /// </summary>
        internal static string TipGetCustomExtFailed {
            get {
                return ResourceManager.GetString("TipGetCustomExtFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动提取图片扩展名失败！ 的本地化字符串。
        /// </summary>
        internal static string TipGetImageExtFailed {
            get {
                return ResourceManager.GetString("TipGetImageExtFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹路径不能为空 的本地化字符串。
        /// </summary>
        internal static string TipPathNotNull {
            get {
                return ResourceManager.GetString("TipPathNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右键菜单添加成功！ 的本地化字符串。
        /// </summary>
        internal static string TipRegister {
            get {
                return ResourceManager.GetString("TipRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新添加菜单成功！ 的本地化字符串。
        /// </summary>
        internal static string TipReRegister {
            get {
                return ResourceManager.GetString("TipReRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义规则格式不正确，请重新修改 的本地化字符串。
        /// </summary>
        internal static string TipRulesError {
            get {
                return ResourceManager.GetString("TipRulesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加右键菜单时，请以管理员的身份运行本软件！ 的本地化字符串。
        /// </summary>
        internal static string TipRunAsAdmin {
            get {
                return ResourceManager.GetString("TipRunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败，请选择正确的扩展名 的本地化字符串。
        /// </summary>
        internal static string TipSaveFailed {
            get {
                return ResourceManager.GetString("TipSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右键菜单移除成功！ 的本地化字符串。
        /// </summary>
        internal static string TipUnRegister {
            get {
                return ResourceManager.GetString("TipUnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到右键菜单“粘贴为文件”中的路径与现在的软件启动路径不同，是否重新添加右键菜单？ 的本地化字符串。
        /// </summary>
        internal static string TipWrongValueInMenu {
            get {
                return ResourceManager.GetString("TipWrongValueInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴为文件 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前你可以使用设置功能 的本地化字符串。
        /// </summary>
        internal static string TxtCanOnlyUse {
            get {
                return ResourceManager.GetString("TxtCanOnlyUse", resourceCulture);
            }
        }
    }
}
