//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteEx.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasteEx.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Paste As File 的本地化字符串。
        /// </summary>
        internal static string MenuPasteAsFile {
            get {
                return ResourceManager.GetString("MenuPasteAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Paste As File 的本地化字符串。
        /// </summary>
        internal static string MenuQuickPasteAsFile {
            get {
                return ResourceManager.GetString("MenuQuickPasteAsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard is empty, still enter the main interface? 的本地化字符串。
        /// </summary>
        internal static string TipAnalyzeFailed {
            get {
                return ResourceManager.GetString("TipAnalyzeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The clipboard content is empty or not supported 的本地化字符串。
        /// </summary>
        internal static string TipAnalyzeFailedWithoutPrompt {
            get {
                return ResourceManager.GetString("TipAnalyzeFailedWithoutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination folder must be empty. 的本地化字符串。
        /// </summary>
        internal static string TipDestinationFolderMustBeEmpty {
            get {
                return ResourceManager.GetString("TipDestinationFolderMustBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download 的本地化字符串。
        /// </summary>
        internal static string TipDownloadFailed {
            get {
                return ResourceManager.GetString("TipDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For the first start, whether to add &quot;Paste As File&quot; to the system context menu? 的本地化字符串。
        /// </summary>
        internal static string TipFirstRegister {
            get {
                return ResourceManager.GetString("TipFirstRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom extension rule matching error, please check the rules! 的本地化字符串。
        /// </summary>
        internal static string TipGetCustomExtFailed {
            get {
                return ResourceManager.GetString("TipGetCustomExtFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to automatically extract picture extensions! 的本地化字符串。
        /// </summary>
        internal static string TipGetImageExtFailed {
            get {
                return ResourceManager.GetString("TipGetImageExtFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot keys already be in use. 的本地化字符串。
        /// </summary>
        internal static string TipHotkeyBeInUse {
            get {
                return ResourceManager.GetString("TipHotkeyBeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid hot keys. 的本地化字符串。
        /// </summary>
        internal static string TipHotkeyInvalid {
            get {
                return ResourceManager.GetString("TipHotkeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Couldn&apos;t register the hot key. 的本地化字符串。
        /// </summary>
        internal static string TipHotkeyRegisterFailed {
            get {
                return ResourceManager.GetString("TipHotkeyRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid characters in a file name 的本地化字符串。
        /// </summary>
        internal static string TipInvalidFileNameChars {
            get {
                return ResourceManager.GetString("TipInvalidFileNameChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor started in tray icon. 的本地化字符串。
        /// </summary>
        internal static string TipMonitorImHere {
            get {
                return ResourceManager.GetString("TipMonitorImHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The monitor process already exists.Two monitors can not exist at the same time！ 的本地化字符串。
        /// </summary>
        internal static string TipMonitorProcessExisted {
            get {
                return ResourceManager.GetString("TipMonitorProcessExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Command. 的本地化字符串。
        /// </summary>
        internal static string TipParseCommandActionError {
            get {
                return ResourceManager.GetString("TipParseCommandActionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t parse incoming parameters. Make sure that the second parameter begins with &apos;-&apos; 的本地化字符串。
        /// </summary>
        internal static string TipParseCommandError {
            get {
                return ResourceManager.GetString("TipParseCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder path cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string TipPathNotNull {
            get {
                return ResourceManager.GetString("TipPathNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading...{0}% 的本地化字符串。
        /// </summary>
        internal static string TipPictureDownloading {
            get {
                return ResourceManager.GetString("TipPictureDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right-click context menu added successfully! 的本地化字符串。
        /// </summary>
        internal static string TipRegister {
            get {
                return ResourceManager.GetString("TipRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The format of the rule is incorrect and will not be enabled. 的本地化字符串。
        /// </summary>
        internal static string TipRulesError {
            get {
                return ResourceManager.GetString("TipRulesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When adding a context menu, please run this software as Administrator! 的本地化字符串。
        /// </summary>
        internal static string TipRunAsAdmin {
            get {
                return ResourceManager.GetString("TipRunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save failed, please select the correct extension. 的本地化字符串。
        /// </summary>
        internal static string TipSaveFailed {
            get {
                return ResourceManager.GetString("TipSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified path does not exist. 的本地化字符串。
        /// </summary>
        internal static string TipSpecifiedPathNotExist {
            get {
                return ResourceManager.GetString("TipSpecifiedPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target file {0} already exists. Do you want to overwrite it? 的本地化字符串。
        /// </summary>
        internal static string TipTargetFileExisted {
            get {
                return ResourceManager.GetString("TipTargetFileExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target path does not exist 的本地化字符串。
        /// </summary>
        internal static string TipTargetPathNotExist {
            get {
                return ResourceManager.GetString("TipTargetPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right-click context menu removed successfully! 的本地化字符串。
        /// </summary>
        internal static string TipUnRegister {
            get {
                return ResourceManager.GetString("TipUnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is detected that the path in the &quot;Paste As File&quot; context menu is different from the current software startup path. Do you want to add the right-click menu again? 的本地化字符串。
        /// </summary>
        internal static string TipWrongValueInMenu {
            get {
                return ResourceManager.GetString("TipWrongValueInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PasteEx 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PasteEx 的本地化字符串。
        /// </summary>
        internal static string TitleAppName {
            get {
                return ResourceManager.GetString("TitleAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PasteEx
        ///
        ///Version：{0}
        ///
        ///Open source ：https://github.com/huiyadanli/PasteEx
        ///
        ///If you have questions or suggestions, please create an Issue here. 的本地化字符串。
        /// </summary>
        internal static string TxtAbout {
            get {
                return ResourceManager.GetString("TxtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently you can only use settings 的本地化字符串。
        /// </summary>
        internal static string TxtCanOnlyUse {
            get {
                return ResourceManager.GetString("TxtCanOnlyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s the latest version 的本地化字符串。
        /// </summary>
        internal static string TxtLatestVersin {
            get {
                return ResourceManager.GetString("TxtLatestVersin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is a new version:  的本地化字符串。
        /// </summary>
        internal static string TxtNewVersion {
            get {
                return ResourceManager.GetString("TxtNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong version number:  的本地化字符串。
        /// </summary>
        internal static string TxtWrongVersion {
            get {
                return ResourceManager.GetString("TxtWrongVersion", resourceCulture);
            }
        }
    }
}
